recipes/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :recipes

end

recipes/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	has_many :recipe_ingredients
	has_many :recipes, :through => :recipe_ingredients
end

recipes/app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :recipe_ingredients, dependent: :destroy
	has_many :ingredients, :through => :recipe_ingredients
	accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true
	validates :name, presence: true, length: {minimum: 2}
end

recipes/app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
  belongs_to :unit
  accepts_nested_attributes_for :ingredient
end

recipes/app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :recipe_ingredients
end

recipes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

recipes/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new
		@recipe = Recipe.new
		@recipe_ingredients = @recipe.recipe_ingredients.build
		@ingredients = @recipe_ingredients.build_ingredient
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def create
		@recipe = Recipe.new(recipe_params)

		if @recipe.save
			redirect_to @recipe
		else
			render 'new'
		end
	end

	def update
		@recipe = Recipe.find(params[:id])

		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy

		redirect_to recipes_path
	end

	private
		def recipe_params
			params.require(:recipe).permit(:name, :directions, recipe_ingredients_attributes: [:id, :recipe_id, :ingredient_id, :unit_id, :amount, :_destroy, ingredient_attributes: [:id]])
		end
end

recipes/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

recipes/app/helpers/application_helper.rb
module ApplicationHelper
end

recipes/app/helpers/recipes_helper.rb
module RecipesHelper
end

recipes/app/helpers/welcome_helper.rb
module WelcomeHelper
end

recipes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

recipes/app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>

	<% if @recipe.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@recipe.errors.count, "error") %> prohibited 
				this recipe from being saved:
			</h2>
			<ul>
				<% @recipe.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<%= f.fields_for :recipe_ingredients do |r| %>
		<p>
		Ingredients<br>
		<%= r.text_field :amount, :size => 5 %> &nbsp; 
		<%= r.collection_select :unit_id, Unit.order('name ASC'), :id, :name %> &nbsp;
		<%= text_field :ingredient, :name%>
		</p>
	<% end %>

	<p>
		<%= f.label :directions %><br>
		<%= f.text_area :directions %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

recipes/app/views/recipes/edit.html.erb
<h1>Edit recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

recipes/app/views/recipes/index.html.erb
<h1>Recipes</h1>

<%= link_to 'New recipe', new_recipe_path %>

<table>
	<tr>
		<th>Name</th>
		<th>Directions</th>
	<tr>

	<% @recipes.each do |recipe| %>
		<tr>
			<td><%= recipe.name %></td>
			<td><%= recipe.directions %></td>
			<td><%= link_to 'Show', recipe_path(recipe) %></td>
			<td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
			<td><%= link_to 'Destroy', recipe_path(recipe),
			method: :delete,
			data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

recipes/app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

recipes/app/views/recipes/show.html.erb
<p>
	<strong>Name:</strong>
	<%= @recipe.name %>
</p>

<p>
	<strong>Ingredients:</strong><br>
	<%= @recipe.recipe_ingredients[0].amount %>
	<%= @recipe.recipe_ingredients[0].unit.name %>
</p>

<p>
	<strong>Directions:</strong><br>
	<%= @recipe.directions %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

recipes/app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<%= link_to 'All Recipes', controller: 'recipes' %>